### ISSUE TITLE
Input required and not supplied: expire-in

### ISSUE THREAD

**Issue by prewk** [kolpav/purge-artifacts-action#1]
I tried your workflow with `expire-in-days: 0`:

```yaml
name: 'Delete all artifacts'
on:
    schedule:
        - cron: '0 * * * *' # every hour

jobs:
    delete-artifacts:
        runs-on: ubuntu-latest
        steps:
            - uses: kolpav/purge-artifacts-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  expire-in-days: 0 # Setting this to 0 will delete all artifacts
```

It errored with `Input required and not supplied: expire-in`
